#!/usr/bin/python3
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer


PAGES = {
    "/view": b'<!doctype html><html><body style="background:#000;color:#fff;font-size:96px">VIEW &#x1F600;</body></html>',
    "/roundview": b'<!doctype html><html><body style="background:#fff;color:#000;font-size:96px">ROUNDVIEW</body></html>',
}


class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        body = PAGES.get(self.path.split("?", 1)[0])
        if body is None:
            self.send_error(404)
            return
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)


ThreadingHTTPServer(("192.168.4.1", 80), Handler).serve_forever()
